// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PontoScripts.Data;

#nullable disable

namespace PontoScripts.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260329105343_AddUsuario")]
    partial class AddUsuario
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("PontoScripts.Models.GlobalizacaoEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AtributoAdicional")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("TEXT");

                    b.Property<string>("Mensagem")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("TEXT");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("TEXT");

                    b.Property<string>("TraducaoEnUS")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TraducaoEsES")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TraducaoPtBR")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Tipo", "Mensagem")
                        .IsUnique();

                    b.ToTable("GlobalizacaoEntries");
                });

            modelBuilder.Entity("PontoScripts.Models.ScriptAlteracaoEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Branch")
                        .HasColumnType("TEXT");

                    b.Property<string>("CriadoPor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NumeroOS")
                        .HasColumnType("TEXT");

                    b.Property<int>("OrdemExecucao")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ScriptSql")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ScriptAlteracaoEntries");
                });

            modelBuilder.Entity("PontoScripts.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Ativo")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Perfil")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("PontoScripts.Models.Versao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataGeracao")
                        .HasColumnType("TEXT");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Observacoes")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Versoes");
                });

            modelBuilder.Entity("PontoScripts.Models.VersaoGlobalizacao", b =>
                {
                    b.Property<int>("VersaoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GlobalizacaoEntryId")
                        .HasColumnType("INTEGER");

                    b.HasKey("VersaoId", "GlobalizacaoEntryId");

                    b.HasIndex("GlobalizacaoEntryId");

                    b.ToTable("VersaoGlobalizacoes");
                });

            modelBuilder.Entity("PontoScripts.Models.VersaoScript", b =>
                {
                    b.Property<int>("VersaoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ScriptAlteracaoEntryId")
                        .HasColumnType("INTEGER");

                    b.HasKey("VersaoId", "ScriptAlteracaoEntryId");

                    b.HasIndex("ScriptAlteracaoEntryId");

                    b.ToTable("VersaoScripts");
                });

            modelBuilder.Entity("PontoScripts.Models.VersaoGlobalizacao", b =>
                {
                    b.HasOne("PontoScripts.Models.GlobalizacaoEntry", "GlobalizacaoEntry")
                        .WithMany("VersaoGlobalizacoes")
                        .HasForeignKey("GlobalizacaoEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PontoScripts.Models.Versao", "Versao")
                        .WithMany("VersaoGlobalizacoes")
                        .HasForeignKey("VersaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GlobalizacaoEntry");

                    b.Navigation("Versao");
                });

            modelBuilder.Entity("PontoScripts.Models.VersaoScript", b =>
                {
                    b.HasOne("PontoScripts.Models.ScriptAlteracaoEntry", "Script")
                        .WithMany("VersaoScripts")
                        .HasForeignKey("ScriptAlteracaoEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PontoScripts.Models.Versao", "Versao")
                        .WithMany("VersaoScripts")
                        .HasForeignKey("VersaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Script");

                    b.Navigation("Versao");
                });

            modelBuilder.Entity("PontoScripts.Models.GlobalizacaoEntry", b =>
                {
                    b.Navigation("VersaoGlobalizacoes");
                });

            modelBuilder.Entity("PontoScripts.Models.ScriptAlteracaoEntry", b =>
                {
                    b.Navigation("VersaoScripts");
                });

            modelBuilder.Entity("PontoScripts.Models.Versao", b =>
                {
                    b.Navigation("VersaoGlobalizacoes");

                    b.Navigation("VersaoScripts");
                });
#pragma warning restore 612, 618
        }
    }
}
